@url = https://8080-violet-lemming-iojnozds.ws-us20.gitpod.io

GET {{url}}/filmes

###

POST {{url}}/filmes 
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
PUT  {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

###
DELETE {{url}}/filmes
Content-Type: application/json

{
    "id" : 5
}