@url = https://8080-green-chicken-qrzf4s3f.ws-us17.gitpod.io/filmes

GET {{url}}/filmes

###

POST {{url}}/filmes 
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
PUT  {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}